### ISSUE TITLE
generitech{1.10.2-0.1.0.184} crashes dedicated Forge 1.10.2 build 2010 on startup

### ISSUE THREAD

**Issue by kreezxil** [AlgorithmicsAnonymous/generitech#19]
Issue:  generitech{1.10.2-0.1.0.184} crashes dedicated Forge 1.10.2 build 2010 on startup

crash report:
https://gist.github.com/8beeb336534e9da59584a3b1c7860fe7

fml server latest:
https://gist.github.com/e29d77d339def1c69dda5bdb20b4ced5

**Comment by SeanLatimer** [comment]
Should be fixed now. Try the latest build on CurseForge and let me know if you have any problems with it
