### ISSUE TITLE
Lighting flicker with furnaces

### ISSUE THREAD

**Issue by Dragnier** [AlgorithmicsAnonymous/generitech#20]
Every time one item finishes in the furnace, the light it gives off goes out and immediately comes back at the start of the next item. This is very annoying; especially with the higher tier furnace because of the speed at which this occurs.

**Comment by Dragnier** [comment]
Now they don't emit light at all. That's not fixing, that's removing. There should be a way to have the light be constant while the machine is on and only go off once it's done, since the vanilla furnaces and other mod furnaces do it.

**Comment by SeanLatimer** [comment]
I did not remove the light emission, I lowered the light level alongside attempting to fix the issue. Obviously the fix I tried worked in dev but not obfuscated

**Comment by Sandvoxel** [comment]
I have fixed the problem in the latest commit
