### ISSUE TITLE
GuiConfig class is being attempted to be accesed during server PreInit causing ClassNotFoundException

### ISSUE THREAD

**Issue by marchermans** [AlgorithmicsAnonymous/generitech#23]
Hello guys,

during testing your mod we found the following exception:
@http://pastebin.com/f1y9EiiN

Debugging it a bit further and looking through the code, you guys seem the be trying to acces the GuiConfig class on the server side somehow. Could you try to fix this, i am willing to help as much as i can.

**Comment by insuusvenerati** [comment]
Hmm this was supposed to have been fixed with #19

**Comment by insuusvenerati** [comment]
Are you running the latest version from Curse?

**Comment by insuusvenerati** [comment]
Does this happen when you place a machine down?

**Comment by marchermans** [comment]
Nopen tanks for thee info
